console.log('%cLoading narrative', 'color: blue')

const para0 = `A woman slides onto the stool next to you. She's buoyant, energetic, dangerously cheerful. It takes a single look to size her up: she's not wearing a wetsuit but instead a short floral-print dress and outlandish sun hat. She's a <span id=nub class=tip>nub</span>.<br><br>She's sized you up in the same time.<br><br>"What's that?" she asks. She wants to know about the tablet in front of you, the one right next to your bowl of hot noodles. The bartender hands this young woman a drink, a shirley temple you'd guess, and the woman shrugs and carries the drink to a nearby bubble window.<br><br>Outside it you can see the deep ocean particulate float like moths. Beyond that is the darkness. What mariners call the <span id=deepSix class=tip>Deep Six.</span><br><br>You turn back to your tablet. What were you looking at again?`

const para1 = `Maybe it's the years that have gotten to you, maybe it's the shit quality of the booze around here. Either way, you're tired. At one point this bar carried real dirt grown food. Now it's all <span class='tip' id='hydro'>hydro</span>. You're old enough, you can tell the difference. These noodles sure weren't made from dirt grown rice.</br></br>But what's to be done? <br><br>You collect your belongings. The sub'll leave in thirty, and it's six decks below. And to think, twenty-four decks above and then another mile up is the surface of the Atlantic. Slick with oil, boiling with storms. Deadly.</br></br>Yeah, as if you're safer down here.</br></br>The tablet pings before you reach the dock. Everything's on schedule, the crew's just waiting for you. If only they'd put elevators in this place, here you are descending a stairwell while exposed pipes drizzle condensation above your head. As you walk onto the docking deck and into your sub bay, a woman passes you and then stops and says, "Morning captain. Don't head off yet, I haven't gotten your torpedoes onto the ship." </br></br>It takes a second to register. Why were they marked as delivered on the tablet? She's burly, a <span id='sixsixsix' class='tip'>six-six-sixer</span> with a goat's skull tattooed across her bald scalp and piercings that sprout across her face.`

const para2 = `Not just wetsuits, but <span id=harpoon class=tip>harpoons</span> and small knives, the best in compressed oxygen tanks and survival water filters. You touch a particularly enticing pair of flippers and a popup blocks your view with 'Ten Best Old World Salvage Spots'. The ruins of <span id = 'newYork' class = 'tip'>New York City</span> top the list, as always. You'd have to charter a submarine to get there, or of course swim five hundred miles sideways and a mile up with those sick polydurable flippers.<br><br>The young woman returns suddenly. "You ever been?" She darts into her shirley temple for a sip. "I hear it's totally flooded, but mutants live on the highest buildings. Like, right above surface level."</br></br>She's killing you with that mischievous grin of hers. She says, "Any chance you'd head that way? We could go together!"`

const para3 = `You're not even sure what it is yet. The data slowly unravels before you, dumping a variety of charts onto your screen that make very little sense. You've got a pattern analysis tool running, and one name keeps popping up over and over. 'Huebert Livingston.'<br><br>You signal the bartender and they pass you a drink. Beneath the glass is your payment, a data chip with Admiralty Exchange stock numbers.<br><br>The bartender glances at the charts and the name. They shrug. "Doesn't mean a thing to me."<br><br>You know better than that. It's not greek, or even the name of a person. It's the name of a submarine, and it's docked here at this station. It had just returned from a salvage trip, somewhere like the ruins of <span id='newYork' class='tip'>New York City</span> if you had to guess.<br><br>The bartender looks you in the eye. "Any ideas what this name means?"`

const para4 = `She senses your impatience and works quickly. It takes a little bit of time before she arrives again with four of the weapons perched on a hand cart. She threw in an extra one for the trouble.<br><br>Your crew loads them up, careful not to talk to the woman. The <span id='sixsixsix' class='tip'>six-six-sixers</span> are petty and volatile. You're glad you let this slide.<br><br>The <span class='tip' id='preSub'> pre-sub</span> awaits you.<br><br>Seal and pressurize the submarine, decouple from the moor, activate navigational equipment, full reverse.<br><br>Everything moves smoothly, you've done this job more than a hundred times before. As you move out into the <span id='deepSix' class='tip'>Deep Six</span>, the lights dim automatically to adjust to the darkness. In only a mile the station will be a hazy glow behind you, an angelic halo.<br><br>And you're out there now. Alone. The currents this deep are gentle, they don't rock the submarine. Your crew of five watches their viewscreens lazily before the engineer and another crewperson head off to their bunks.<br><br>Sandy gives you a wave and a nod, she's your navigator and first mate. You're on course, she means, and then she gives her monitor a puzzled look. "There's an SOS up ahead," she says. "<span id='admiralty' class='tip'>Admiralty Board</span>. Black box." <br><br>She's trying her best to look impassive. The Admiralty Board is well supplied, nothing sinks their convoys. Still, you'd get in their good graces if you stopped to help.`

const para5 = `Forget the torpedoes. You haven't run into trouble in the Deep Six for a few months now, and you're expected in <span id=newBrooklyn class=tip>New Brooklyn</span> in ten days. Your professional reputation is unmarred by late deliveries, you decide to keep it that way. <br><br>The <span class=tip id=preSub> pre-sub</span> awaits you.<br><br>Seal and pressurize the submarine, decouple from the moor, activate navigational equipment, full reverse.<br><br>Everything moves smoothly, you've done this job more than a hundred times before. As you move out into the <span id=deepSix class=tip>Deep Six</span>, the lights dim automatically to adjust to the darkness. In only a mile the station will be a hazy glow behind you, an angelic halo.<br><br>`

const para6 = `You argue. You're on a schedule you say. You mention your distaste for these juvenile devil worshippers. They're basically irresponsible teens. You'd have ignored her completely if she wasn't the only dealer in armaments on this <span id='hab' class='tip'>hab</span>. <br><br>She scowls and leaves.<br><br>You head into the submarine and begin your <span id='preSub' class='tip'>pre-sub</span>. Your first mate Sandy calibrates the navigation map and you're checking perishables when Eddie calls you from the pilot seat. You hurry up and see what he sees: about twelve or so six-six-sixers, some of them with knives and harpoons, one with an old double edged sword. And the two with blowtorches.<br><br>"We've gotta go," says Eddie as the woman and her group stride forward. "We've gotta go!"<br><br>You immediately jam the red alert and everything inside the sub turns a shade of crimson. Eddie throws the switch on the docking moor and also the reverse. The moor cracks, probably unusable. Backing and submerging at the same time, all the while the six-six-sixers leap up onto the hull. You hear the sound of the blowtorches.<br><br>And they stop, these angry hornets run off suddenly. You'll get out of the station. The submarine is still pressurizing and the billions of pounds of water overhead are squeezing in through small cracks here and there. Bend so you do not break. You'll have to vent some of your precious O2 but that's life.<br><br>"Captain," says Sandy, "Outside!" <br><br>Where? You take a look at her viewscreen and see a dangerous looking submarine directly behind you, its markings belongs to the six-six-sixers. Of course they're out here.`

const para7 = `A quick shrug and you're off with your datachip, a quick shrug you hope comes off as genuine show of 'who gives a fuck, my job is done'. The bartender watches as you leave but they say nothing. <br><br> And outside the noodle bar, in the corridor just large enough for two people to pass uncomfortably, in the light of a bleak, static neon sign of noodles, you walk at an unconcerned pace. You've been moving through the corridors of this hab for a while now. You know when you'll be followed and you know who'll do the following. Probably not the bartender, likely it's one of their contacts.<br><br>Whoever it is has managed to avoid direct line of sight, but you've got tricks up your sleeve. You slip into a nearby crowded coffee shop with 'coffee' being the loose term for a brown <span class=tip id=hydro>hydro</span> sludge they serve. There's a security camera here, one you surreptitiously key your tablet into. You can watch the feed from a table.<br><br>This shadow on your tail is pretty uninteresting. A medium person of medium build and medium height, utterly androgynous with a normal shade of brownish hair. In other words, you wouldn't be able to describe them if you needed to.`

const para8 = `It's a quick game of cat and mouse. You walk through a crowd of affluent tourists and then duck into a nearby eatery. The shadow follows, but you're already a step ahead. You're bustling through the kitchen, asking where the clean aprons are, you work here now. And then out a delivery hatch, onto the service level between this hab's main causeway and the bulkhead, down a ladder that leads to the docking level.<br><br>You check over your shoulder. They're gone. You hate to do this to the bartender but at least they'll understand. A quick lookup on the mooring directory reveals the Huebert Livingston at B-08. You'll take one of the maintenance tunnels.`

const para9 = `Sandy lays in a new heading, ten miles SSW she estimates. That's where the <span id=janus class=tip>JANUS signals</span> are coming from. The message repeats in a loop, the urgent robotic voice occasionally gurgles with static. It's mostly gibberish mixed with strongly worded calls for help.<br><br> "I've never even seen an <span id=admiralty class=tip>Admiralty</span> distress call before," says Sandy. "I think a lot of this is encoded. You know those old movies where people venture into the dark and get picked off one by one? Aliens, demons, homicidal masked men." <br><br>The engineer arrives with some caffeinated hydro sludge she calls coffee. "On duty," she says. "What's all this?"<br><br> Sandy beckons the two of you over. She's got a feed from one of the forward cameras. "Look."<br><br>It's an old industrial station, barely even enough space to be a proper <span id=hab class=tip>hab</span>. You'd guess it's <span id=war class=tip>pre-war</span> although that'd mean it predates the Admiralty Board. There's a single docking moor, and from the admittedly pixelated camera feed it looks very empty.<br><br> "You know all those old movies about abandoned stations?" says Sandy.`

const para10 = `Rust has eaten away the creases of the dock. It's dull red in the beam of your flashlight. Everything here smells just a little bit like iron.<br><br>Your engineer steps out onto the platform and shines the light on your sub's sleek hull. "There's serious flooding in the lower levels of the structure. That's also where the black box is transmitting."<br><br> There's a flurry of movement from the edge of the dock. You swing the flashlight's beam in that direction and see the gleam off a pair of eyes.<br><br> Beady black eyes.<br><br> Piglet eyes. It's a small herd, assuming you call a group of piglets a herd. A brood? A flock? A murder? They're wide eyed and stumbling over each other to stay out of the light.<br><br> Your engineer rolls her eyes but you hear a crackle from the shortwave radio. "Sandy calling on all frequencies, may we keep the piggies? I'm not taking no for an answer."<br><br> The engineer replies, "You'll have to actually step onto the station for that."<br><br> "In that case this rescue operation is a go. I'll have them in the cargo hold in five."<br><br> The piglets quiver in a bunch while your engineer strides down the corridor. She calls back, "That new pig shit you're going to find all over the deck? It's Sandy's responsibility."`

const para10Two = `<br><br> Millions of pounds of pressurized water press against the closed doors here. Some of the doors. You knock each one before opening it. Sometimes it's the hollow sound of air, sometime the dull echo of liquid.<br><br> Finally you give up on finding a safe passage through the structure. You'll have to swim to the black box from the outside.<br><br> The engineer injects some <span id=kinerine class=tip>kinerine</span> into her thigh and looks over towards you. "I hate this shit. Makes me feel nauseous. It's been almost a year since I had to do this."<br><br> It's true. As the chemical from your own syringe begins to bubble through your body you can feel its sickening effects. It'll be gone in a few minutes, and at least you'll be able to dive this deeply without a suit.<br><br> Sandy walks in with an entourage of piglets. "Good luck in all that cramped wreckage. And please don't haunt me if the deep sea aliens get you."<br><br> It takes a few minutes for you to swim from the sub to the structure and a good chunk of it is buried into the mud that coats much of the ocean bottom. You find an opening and squeeze through, engineer just behind you. Your flashlight travels across a hulk of equipment you don't understand.<br><br> You see a body floating above the floor. A cow carcass, its flesh mostly torn away by scavengers like lampreys. And the other things, most of them unnamed.<br><br> A computer terminal is still emitting a green light, partially covered by mud and murk. You wipe it away. There's slime on your glove.<br><br> The terminal has access to the black box. You can download everything you need to from here.`

const para11 = `You read the output. It's mostly gibberish until you get to the mission statement. <br><br>Aria Project Log 11.56<br><br>Trial candidate #67 - No development before sudden brain death - Status - Deceased<br>Trial candidate #68 - Overactivity in the brain stem caused the onset of rapid oxygen deterioration - Status - Deceased<br>Trial candidate #69 - Accidental mismeasurement of serum - Status - Deceased<br>Trial candidate #70 - Although brain activity continues, subject has lost all motor functions - Status - Incapacitated<br>Trial candidate #71 - Has shown increased activity in the brain stem - Status - Healthy<br><br>Progress Report - Human experiments not yet advised, the mortality rate for injection into the brain stem remains high. Spinal injections remain our safest route. The results are predictable but have minimal impact on the subject's heightened alacrity.<br><br>And then you feel the bite. Like a trio of power drills moving through the layers of your suit's mesh and your shoulderblade. You spin around, diving knife at the ready and see it thrash angrily through a cloud of your own blood. Maybe two meters long, thick as your arm, it disappears into the muck.<br><br> Your engineer checks your back and then plugs an optic cable into the terminal. "Not in vain," she <span id=signLang class=tip>signs</span> and readies her <span id=harpoon class=tip>harpoon gun</span> in case the thing . . .<br><br> Back on the sub your engineer Li is patching you up. "Sleep on your stomach," they say. "That's what I think a doctor would say. Also don't move that arm much. Your arm bone's collected to your shoulder bone which is connected to your shattered scapula back here." They pull out a sling. "No more dives for a week. Let the kids have all the fun from now on."<br><br> Your engineer has already uploaded the data to the sub's computer. "I hope someone really likes this," she says. "Enough to cover your hospital bill at <span id=newBrooklyn class=tip>New Brooklyn</span>.<br><br>Sandy picks up an oinking piglet and perches them on her shoulder. "And that's why I don't go on dives."<br><br> You return to the pilot's room while the engineer wanders off to her bunk for a few hours of sleep.`

const para11Two = `<br><br> The going is quiet. Sandy checks her instruments regularly but there's no movement outside. The computer performs constant checks on the passive SONAR but there's not much of substance out in the dark.<br><br> And then the whole submarine lurches to one side. Your head meets a nearby console and there's the sharp pain of metal piercing your flesh.<br><br> Sandy has pulled herself back into the navigator's chair. "Fuck," she says. "Holy shit jesus fucking mary and joseph with a goddamned spoon fuck. It's big, whatever it is."<br><br> The computer alerts you to puncture damage towards the submarine's tail. You immediately get an image from the conning tower looking back.<br><br> "Fuck," says Sandy. "That's big. Those teeth are like the size of my whole fucking arm!"<br><br>You hear the teeth rip away from the bulkhead before you see it on the cam. The thing is in the dark again, but you know it'll come around for another pass.`

const para12 = `At least you saw it squirming out before it reached your head. Not quite a lamprey, they only have one head to this thing's three. The heads nip at your face all the while the body squirms at the end of your diving knife, held an arm's length away. It's powerful, a singularly muscular organism designed for tearing the flesh off of other things. You can see its muscles roil beneath the translucent white skin.<br><br> And then it dislodges itself from the knife and heads out through an opening in the structure. Two or three meters long, heads to tail.<br><br> The engineer is looking at you wide eyed through her mask. And then at the terminal. At some point the thing's tail must've slammed through the monitor because it's shattered, completely black.<br><br> You and the engineer tinker for a little while but with no luck. You start moving through the facility, looking for other terminals but the black box has gone silent. The oxygen monitor on your wrist warns of your impending fate.<br><br> From what you can tell it was a laboratory of some kind. That's all you know.<br><br> The crew seems happy your in one piece, but they're mostly excited by the piglets. "They've got such big heads," says Sandy. "I haven't seen anything that wasn't a cat or a dog in ages, and now I'm surrounded by farm animals."<br><br> "Hey captain, would you consider your friend back in the installation a cat or a dog?" says the engineer.<br><br> Sandy picks up an oinking piglet and perches them on her shoulder. "And that's why I don't go on dives."<br><br> You return to the pilot's room while the engineer wanders off to her bunk for a few hours of sleep.`

const para12Two = para11Two

const para13 = `Millions of pounds of pressurized water press against the closed doors here. Some of the doors. You knock each one before opening it. Sometimes it's the hollow sound of air, sometime the dull echo of liquid.<br><br> Finally you give up on finding a safe passage through the structure. You'll have to swim to the black box from the outside.<br><br> The <span id="aGang" class="tip">A-Ganger</span> injects some <span id=kinerine class=tip>kinerine</span> into her thigh and looks over towards you. "I hate this shit. Makes me feel nauseous. It's been almost a year since I had to do this."<br><br> It's true. As the chemical from your own syringe begins to bubble through your body you can feel its sickening effects. It'll be gone in a few minutes, and at least you'll be able to dive this deeply without a suit.<br><br> Sandy walks in with an entourage of piglets. "Good luck in all that cramped wreckage. And please don't haunt me if the deep sea aliens get you."<br><br> It takes a few minutes for you to swim from the sub to the structure and a good chunk of it is buried into the mud that coats much of the ocean bottom. You find an opening and squeeze through, <span id="aGang" class="tip">A-Ganger</span> just behind you. Your flashlight travels across a hulk of equipment you don't understand.<br><br> You see a body floating above the floor. A cow carcass, its flesh mostly torn away by scavengers like lampreys. And the other things, most of them unnamed.<br><br> A computer terminal is still emitting a green light, partially covered by mud and murk. You wipe it away. There's slime on your glove.<br><br> The terminal has access to the black box. You can download everything you need to from here.<br><br>`

const para14 = `You pick up the hydro sludge they call coffee and carry it back into the corridor, down a side alley of sorts, and then turn and throw it into your pursuer's face. They don't have time to react before you've taken an exposed electrical pipe and pumped an unknown voltage through their wet face.<br><br>They're shivering with electricity on the floor now, their convulsions getting less and less frequent. A quick pat down reveals nothing useful, they'd be a terrible shadow if they had anything like a real passport. You pull the few dollars they have tucked into their wallet and hope the station authority thinks this was a random mugging.<br><br>The thought crosses your mind, maybe it is a random mugging. Maybe this was just a curious coincidence of a human who walked down the wrong corridor at the wrong time. Still, a few bucks is a few bucks.<br><br>Maybe it's your imagination, but this corridor seems startlingly quiet. You can hear the gentle flow of a water pipe between the walls and the bulkhead, even despite the occasional clattering twitch from the shadow.<br><br>A quick lookup of the Huebert Livingston reveals it's moored at B-08.`

const para15 = `There's a couple of toughs guarding the Huebert. Thugs with <span class=tip id=harpoon>harpoon guns</span> clipped to the hips of their wetsuits. A tuxedo patterned cat watches them lazily from the top of the submarine's conning tower. It spots you without alarm and then starts to lick a paw, apparently uninterested in whatever you're about to attempt.<br><br>The thugs look bored until a local <span id=sixsixsix class=tip>six-six-sixer</span> comes into view. He walks up to the head thug (by your estimate) and the two of them argue for a moment while the rest of the armed guards pretend not to listen. They could be arguing over money, or arguing over politics, or arguing over the name of the tuxedo cat who's watching everything with the eyes of a dispassionate observer.<br><br>Finally the six-six-sixer pulls something out of his wetsuit waistband, throws it onto the ground, and spits on the thug's shoe. There's a moment of calculation on the thug's end: how much trouble would a six-six-sixer with a harpoon through the head be? Mercy wins out and the thug swoops up the plastic vial from the ground. The sixer leaves.<br><br>And now the thugs are headed inside the sub. If there's a chance in hell to get onboard, it's now.`

const para16 = `Furtive is a word you'd apply to yourself. After all, you got the data chip that's led all the way here, right? ${getEmployer() ? getEmployer().capitalize() : 'Someone'} will probably love whatever's in Huebert's bowels.<br><br>When the guard turns to pick his nose you scuttle behind him and pass into the shadow of the submarine. He hasn't even flicked what he finds across the mooring before you've crawled into the hatch and found a place behind an exposed pipe to flatten your body and take stock of the situation.<br><br>Someone aboard has decorated the Livingston with pictures of greenery and wrapped weathered plastic ivy along the exposed pipes of the ceiling. The brine has sucked away most of their color and turned the iron picture frames a gorgeous color of crimson. You can faintly read the plaque on one of the frames: The Ramble of Central Park,<span class=tip id=newYork> New York, NY</span>.<br><br>The head thug walks by and mutters about how much he wants to put a dent in some unknown person's ribcage. He doesn't see you but turns when you let out an unexpected yelp and starts to walk in your direction.<br><br>The yelp came because you felt a sudden claw on the side of your hand. Not sharp, not incisive, just startling. The tuxedo cat meows and purrs and emerges to the guard from your hiding place.<br><br>'What, you find a mouse?' the guard says. He strokes the cat behind the ears. 'G'boy, your a good lil' murderer aren't ya?' He unceremoniously turns back towards his tasks. The cat loses interest and returns to you, curious about your next plan.`

const para17 = `The cat seems distinctly interested in you. He follows with mercifully quiet footsteps, the pads of his paws quieter than you'll ever be.<br><br>More importantly, the cat seems hears folks walking through the corridor well before you do, and a swivel of an ear always precedes some human's plodding march through the submarine.<br><br>Much more of the submarine has been decorated with cheap plastic things and salt-eaten amenities from old dollar stores on the surface. Even from a few meters away you can smell the distinctive toxic dust that coats everything that comes from above the waves.<br><br>You're finally in the deep bottom of the ship, the cargo hold where you'll probably find something you need to find, something interesting, literally anything besides old loot from the surface.<br><br>One of the storage compartments has a keypad attached to its lock. Very faintly you can make out what look like bloody handprints along the edge of the door where someone grasped the frame. They're faint, but nobody took the time to buff them out.<br><br>There's no chance of figuring out the keypad. Then again, there's a micro-usb at the edge that your own tablet can link into. You just have to hack it.<br><br>The cat stares at the closed steel doorway.`

const para18 = `[-- Try out different combinations of letters and numbers --]<br>[-- The password must be correctly spelled --]<br>[-- The password is case sensitive --]<br>[-- Correctly placed guesses will light up --]<br<br><input type='text' name='hacker-input' id='hacker-input' maxlength=10><br><span id='hacker-input-processed'></span>`

const para19 = `TODO: Add for having hacked through the door`

const para20 = `TODO: Add for giving up on the door`

const para21 = `A couple minutes of fast paced talking proves she's serious. In those two minutes you learn that a submarine already docked with a crew ready to head out to the New York ruins, they have advanced equipment including the brand of harpoon you'd been looking at along with a prototype Sheepshead DD Drone, tech that screams 'I AM FROM THE FUTURE! WORSHIP ME!'<br/><br/>And it's all true, naturally, you find the submarine manifest on this <span id=hab class=tip>hab's</span> mooring directory, available for all to see.<br/><br/>There comes a point an hour later when you're not even sure you've moved of your own volition. You're loading a torpedo onto the sub with the help of burly but affable man in floral print shorts. He's wearing the same khaki sunhat as Dali, the young woman. His name is Viktor with a K.<br/><br/>With the final torpedo loaded up Viktor casually takes you aside. "You know this will be a an exciting and challenging trip. Tell me, do you believe the stories of mutants in the ruins of New York?"`

const para22 = `Viktor shrugs. "All made up. Of course, if we found evidence of mutants... If they exist, they hide it well. Put it out of your mind, friend, along with the tales of twenty meter crocodiles and <span id='ghost' class='tip'>sea ghosts</span>."<br/><br/>He ushers you along to the sub's living room, a mildly cramped space with a treadmill, faux leather couch, coffee table and wide screen TV. The entire crew has crowded into this room while the young woman sits with legs folded beneath her on the coffee table. There's something odd about the crew, you haven't placed it yet.<br/><br/>The young woman speaks, you're surprised by the power of her voice. "As you might know, my name is Dali. Like the artist, not the country singer."<br/><br/>The crew chuckles a little.<br/><br/>"We're headed out to the New York ruins, I estimate the trip'll take roughly a week. We're doing a salvage operation and if you have any questions or concerns I'd like you to bring it up with Viktor, he's head of that team.<br/><br/>"Most of you are here as deck hands. This submarine's name is Klebnikov. He's an older Nelson class and he needs more supervision than the corporate subs most people use today. There's no onboard computer. Get to know him."<br/><br/>Dali starts to assign the crew tasks and as she goes through them you finally piece together what had troubled you. About a third of the crew aren't wearing wetsuits, they have the same floral print clothing and khaki sunhats that Viktor and Dali wear.`

const para23 = `TODO: Add this paragraph(23)`

const para24 = `TODO: Add this paragraph(24)`

const para25 = `TODO: Add this paragraph(25)`

const para26 = `TODO: Add this paragraph(26)`

const para27 = `TODO: Add this paragraph(27)`

const para28 = `TODO: Add this paragraph(28)`

const para29 = `TODO: Add this paragraph(29)`

const para30 = `TODO: Add this paragraph(30)`

const para31 = `TODO: Add this paragraph(31)`

const para32 = `TODO: Add this paragraph(32)`

const para33 = `TODO: Add this paragraph(33)`

console.log('%cNarrative loaded', 'color: purple')
